version: '3.7'
services:

  tlbx-trees-sql:
    container_name: tlbx-trees-sql
    build:
      context: .
      dockerfile: sql.dockerfile
    image: tlbx-trees-sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"

  tlbx-trees-redis:
    container_name: tlbx-trees-redis
    image: redis:5.0.8-alpine
    ports:
    - "6379:6379"

  tlbx-trees-minio:
    container_name: tlbx-trees-minio
    image: minio/minio:RELEASE.2020-08-05T21-34-13Z
    environment:
      MINIO_ACCESS_KEY: localtest
      MINIO_SECRET_KEY: localtest
    ports:
    - "9000:9000"
    command: "minio server /data"