version: '3.7'
services:

  tlbx-testall-sql:
    container_name: tlbx-testall-sql
    build:
      context: ../.
      dockerfile: docker/sql.dockerfile
    image: tlbx-testall-sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"

  tlbx-testall-redis:
    container_name: tlbx-testall-redis
    image: redis:5.0.8-alpine
    ports:
    - "6379:6379"

  tlbx-testall-minio:
    container_name: tlbx-testall-minio
    image: minio/minio:RELEASE.2020-08-05T21-34-13Z
    environment:
      MINIO_ACCESS_KEY: localtest
      MINIO_SECRET_KEY: localtest
    ports:
    - "9000:9000"
    command: "minio server /data"