version: '3.7'
services:

  tlbx-sql-testall:
    container_name: tlbx-sql-testall
    build:
      context: ../.
      dockerfile: docker/sql.dockerfile
    image: tlbx-sql-testall
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
    - "3306:3306"

  tlbx-redis-testall:
    container_name: tlbx-redis-testall
    image: redis:5.0.8-alpine
    ports:
    - "6379:6379"

  tlbx-minio-testall:
    container_name: tlbx-minio-testall
    image: minio/minio:RELEASE.2020-08-05T21-34-13Z
    environment:
      MINIO_ACCESS_KEY: localtest
      MINIO_SECRET_KEY: localtest
    ports:
    - "9000:9000"
    command: "minio server /data"