// Code generated by qtc from "fcm.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package fcm

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamqryGetTokens(qw422016 *qt422016.Writer) {
	qw422016.N().S(`SELECT DISTINCT f.token FROM fcmTokens f JOIN users u ON f.user=u.id WHERE topic=? AND u.fcmEnabled=1 `)
}

func writeqryGetTokens(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamqryGetTokens(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func qryGetTokens() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writeqryGetTokens(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
