// Code generated by qtc from "fcm.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line fcm.sql:1
package fcm

//line fcm.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line fcm.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line fcm.sql:1
func streamqryGetTokens(qw422016 *qt422016.Writer) {
//line fcm.sql:2
	qw422016.N().S(`SELECT DISTINCT f.token FROM fcmTokens f JOIN users u ON f.user=u.id WHERE topic=? AND u.fcmEnabled=1 `)
//line fcm.sql:9
}

//line fcm.sql:9
func writeqryGetTokens(qq422016 qtio422016.Writer) {
//line fcm.sql:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line fcm.sql:9
	streamqryGetTokens(qw422016)
//line fcm.sql:9
	qt422016.ReleaseWriter(qw422016)
//line fcm.sql:9
}

//line fcm.sql:9
func qryGetTokens() string {
//line fcm.sql:9
	qb422016 := qt422016.AcquireByteBuffer()
//line fcm.sql:9
	writeqryGetTokens(qb422016)
//line fcm.sql:9
	qs422016 := string(qb422016.B)
//line fcm.sql:9
	qt422016.ReleaseByteBuffer(qb422016)
//line fcm.sql:9
	return qs422016
//line fcm.sql:9
}
