version: '3.7'
services:

  tlbx-sql-todo:
    container_name: tlbx-sql-todo
    build:
      context: ../../.
      dockerfile: cmd/todo/sql.dockerfile
    image: tlbx-sql-todo
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
    - "3306:3306"

  tlbx-redis-todo:
    container_name: tlbx-redis-todo
    image: redis:5.0.8-alpine
    ports:
    - "6379:6379"