version: '3.7'
services:

  tlbx-sql-trees:
    container_name: tlbx-sql-trees
    build:
      context: ../../.
      dockerfile: cmd/trees/sql.dockerfile
    image: tlbx-sql-trees
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
    - "3306:3306"

  tlbx-redis-trees:
    container_name: tlbx-redis-trees
    image: redis:5.0.8-alpine
    ports:
    - "6379:6379"