DROP DATABASE IF EXISTS pwds;
CREATE DATABASE pwds;
USE pwds;

DROP TABLE IF EXISTS pwds;
CREATE TABLE pwds(
	id BINARY(16) NOT NULL,
	salt   VARBINARY(256) NOT NULL,
	pwd    VARBINARY(256) NOT NULL,
	n      MEDIUMINT UNSIGNED NOT NULL,
	r      MEDIUMINT UNSIGNED NOT NULL,
	p      MEDIUMINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);

DROP USER IF EXISTS 'pwds'@'%';
CREATE USER 'pwds'@'%' IDENTIFIED BY 'C0-Mm-0n-Pwd5';
GRANT SELECT ON pwds.* TO 'pwds'@'%';
GRANT INSERT ON pwds.* TO 'pwds'@'%';
GRANT UPDATE ON pwds.* TO 'pwds'@'%';
GRANT DELETE ON pwds.* TO 'pwds'@'%';
GRANT EXECUTE ON pwds.* TO 'pwds'@'%';