name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: Test
      run: ./bin/pre gh-actions
      
    - name: Convert go coverage to lcov format
      uses: jandelgado/gcov2lcov-action@v1.0.8
      
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}