name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: Test
      run: ./bin/pre gh-actions
      
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path-to-profile: coverage.out